[package]
name = "mc"
version = "0.0.1"
edition = "2018"
authors = ["Andrey Kolev"]
[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = { version = "0.9.2", features = ["small_rng"] }
rand_distr = "0.5.1"
rayon = "1.11.0"
serde = "1.0"
serde_json = "1.0"
