[package]
name = "hmc"
version = "0.0.1"
edition = "2018"
authors = ["Andrey Kolev"]
[dependencies]
ndarray = "0.17.1"
ndarray-rand = "0.16.0"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

